server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
#    gateway:
#      mvc:
#        routes:
#          - id: customers-route
#            uri: http://localhost:8081
#            predicates:
#              - Path= /customers/**
#          - id: inventory-route
#            uri: http://localhost:8082
#            predicates:
#              - Path= /products/**